# Generated by Django 6.1 on 2026-08-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
